settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: go-gin-demo
  path: .
  commands: {}
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
server:
  status: true
  open: false
  port: 9090
  host: localhost
